services:
- type: web
  name: wordpress
  env: docker
  plan: standard
  disk:
    name: wordpress
    mountPath: /var/www/html
    sizeGB: 20
  envVars:
  - key: WORDPRESS_DB_HOST
    fromService:
      name: mysql-wordpress
      type: pserv
      property: host
  - key: WORDPRESS_DB_NAME
    value: mysql
  - key: WORDPRESS_DB_USER
    value: mysql
  - key: WORDPRESS_DB_PASSWORD
    value: mysql
- type: pserv
  name: mysql-wordpress
  env: docker
  plan: standard
  disk:
    name: mysql-wordpress
    mountPath: /var/lib/mysql
    sizeGB: 20
  envVars:
  - fromGroup: mysql-wordpress

envVarGroups:
- name: mysql-wordpress
  envVars:
  - key: MYSQL_DATABASE
    value: mysql
  - key: MYSQL_USER
    value: mysql
  - key: MYSQL_PASSWORD
    generateValue: true
  - key: MYSQL_ROOT_PASSWORD
    generateValue: true
